import Head from 'next/head';
import React from 'react';
import Header from './Header';

type Props = {
  title: string;
  children: React.ReactNode;
};

function Layout({ title, children }: Props) {
  return (
    <div className="mx-auto max-w-5xl">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main>{children}</main>
      <footer>footer</footer>
    </div>
  );
}

export default Layout;
